name: my-workflow1

on: [push]

jobs:
  my-job1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Isstall Dependemcies
      run: npm ci

    - name: Execute Lint
      run: npm run lint

    
 